apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monitoring-kpo-leader-election
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/component: prometheus-operator
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monitoring-kpo-leader-election
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-prometheus-stack
    app.kubernetes.io/component: prometheus-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monitoring-kpo-leader-election
subjects:
- kind: ServiceAccount
  name: monitoring-kube-prometheus-operator
  namespace: monitoring