images:
  urlService:
    tag: sha-90c255a
  redirectService:
    tag: sha-79333d2
  analyticsService:
    tag: sha-38d7c13
  frontendService:
    tag: sha-a390c2e
replicaCount:
  urlService: 2
  redirectService: 2
  analyticsService: 1
  frontendService: 1
  postgres: 1
ingress:
  hosts:
    api: api.stg.galhalevi.dev
    redirect: r.stg.galhalevi.dev
    analytics: analytics.stg.galhalevi.dev
    frontend: app.stg.galhalevi.dev
urlService:
  baseUrl: http://r.stg.galhalevi.dev
frontendService:
  apiUrl: "https://api.stg.galhalevi.dev"
global:
  appEnv: stg
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
