images:
  urlService:
    tag: sha-f3476f2
  redirectService:
    tag: sha-79333d2
  analyticsService:
    tag: sha-f3476f2
  frontendService:
    tag: sha-af7837d
replicaCount:
  urlService: 2
  redirectService: 2
  analyticsService: 1
  frontendService: 1
  postgres: 1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: url-platform-stg-tls
      hosts:
        - api.stg.galhalevi.dev
        - r.stg.galhalevi.dev
        - analytics.stg.galhalevi.dev
        - app.stg.galhalevi.dev
  hosts:
    api: api.stg.galhalevi.dev
    redirect: r.stg.galhalevi.dev
    analytics: analytics.stg.galhalevi.dev
    frontend: app.stg.galhalevi.dev
urlService:
  baseUrl: "https://r.stg.galhalevi.dev"
  corsOrigins: "https://app.stg.galhalevi.dev"
analyticsService:
  corsOrigins: "https://app.stg.galhalevi.dev"
frontendService:
  analyticsUrl: "https://analytics.stg.galhalevi.dev"
  apiUrl: "https://api.stg.galhalevi.dev"
global:
  appEnv: stg
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
