images:
  urlService:
    tag: sha-198b076
  redirectService:
    tag: sha-f8f08fe
  analyticsService:
    tag: sha-f8f08fe
  frontendService:
    tag: sha-e9f9c49
replicaCount:
  urlService: 3
  redirectService: 3
  analyticsService: 2
  frontendService: 2
  postgres: 1
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "86400"
  tls:
    - secretName: url-platform-prod-tls
      hosts:
        - api.galhalevi.dev
        - r.galhalevi.dev
        - analytics.galhalevi.dev
        - app.galhalevi.dev
  hosts:
    api: api.galhalevi.dev
    redirect: r.galhalevi.dev
    analytics: analytics.galhalevi.dev
    frontend: app.galhalevi.dev
urlService:
  baseUrl: "https://r.galhalevi.dev"
  corsOrigins: "https://app.galhalevi.dev"
analyticsService:
  corsOrigins: "https://app.galhalevi.dev"
frontendService:
  analyticsUrl: "https://analytics.galhalevi.dev"
  apiUrl: "https://api.galhalevi.dev"
global:
  appEnv: prod
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
backup:
  enabled: true
  storageAccount: "urlplatbackup" # must match var.backup_storage_account_name in 00-network tfvars
