apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: url-service-slo-latency
  labels:
    release: monitoring
spec:
  groups:
    - name: url-service.slo.latency
      rules:
        - alert: UrlServiceLatencySLOFastBurn
          expr: |
            (
              (
                (
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[5m]))
                -
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="0.5"}[5m]))
                )
                /
                clamp_min(sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[5m])), 1e-9)
              )
              / 0.05
            ) > 14
            and
            (
              (
                (
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[1h]))
                -
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="0.5"}[1h]))
                )
                /
                clamp_min(sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[1h])), 1e-9)
              )
              / 0.05
            ) > 14
          for: 2m
          labels:
            severity: page
            service: url-service
          annotations:
            summary: "url-service latency SLO fast burn (p95>500ms)"
            description: "Error budget burn rate is high for both 5m and 1h windows. Users are experiencing sustained high latency."

        - alert: UrlServiceLatencySLOSlowBurn
          expr: |
            (
              (
                (
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[30m]))
                -
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="0.5"}[30m]))
                )
                /
                clamp_min(sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[30m])), 1e-9)
              )
              / 0.05
            ) > 2
            and
            (
              (
                (
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[6h]))
                -
                  sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="0.5"}[6h]))
                )
                /
                clamp_min(sum(rate(http_request_duration_seconds_bucket{namespace="url-platform-dev",service="url-service",le="+Inf"}[6h])), 1e-9)
              )
              / 0.05
            ) > 2
          for: 15m
          labels:
            severity: ticket
            service: url-service
          annotations:
            summary: "url-service latency SLO slow burn (p95>500ms)"
            description: "Error budget burn rate is moderately high for both 30m and 6h windows. Investigate performance regression."