images:
  urlService:
    tag: sha-f3476f2
  redirectService:
    tag: sha-79333d2
  analyticsService:
    tag: sha-f3476f2
  frontendService:
    tag: sha-af7837d
ingress:
  hosts:
    api: api.dev.galhalevi.dev
    redirect: r.dev.galhalevi.dev
    analytics: analytics.dev.galhalevi.dev
    frontend: app.dev.galhalevi.dev
urlService:
  baseUrl: http://r.dev.galhalevi.dev
  corsOrigins: "http://app.dev.galhalevi.dev"
analyticsService:
  corsOrigins: "http://app.dev.galhalevi.dev"
frontendService:
  analyticsUrl: "http://analytics.dev.galhalevi.dev"
  apiUrl: "http://api.dev.galhalevi.dev"
global:
  appEnv: dev
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
