images:
  urlService:
    tag: sha-ae74809
  redirectService:
    tag: sha-ae74809
  analyticsService:
    tag: sha-ae74809
  frontendService:
    tag: sha-e9f9c49
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    - secretName: url-platform-dev-tls
      hosts:
        - api.dev.galhalevi.dev
        - r.dev.galhalevi.dev
        - analytics.dev.galhalevi.dev
        - app.dev.galhalevi.dev
  hosts:
    api: api.dev.galhalevi.dev
    redirect: r.dev.galhalevi.dev
    analytics: analytics.dev.galhalevi.dev
    frontend: app.dev.galhalevi.dev
urlService:
  baseUrl: https://r.dev.galhalevi.dev
  corsOrigins: "https://app.dev.galhalevi.dev"
analyticsService:
  corsOrigins: "https://app.dev.galhalevi.dev"
frontendService:
  analyticsUrl: "https://analytics.dev.galhalevi.dev"
  apiUrl: "https://api.dev.galhalevi.dev"
global:
  appEnv: dev
monitoring:
  serviceMonitor:
    enabled: true
    labels:
      release: monitoring
  prometheusRules:
    availability:
      enabled: true
    latencySLO:
      enabled: true
